### ISSUE TITLE
Broken when used form an addon

### ISSUE THREAD

**Issue by tchak** [tomdale/ember-network#5]
```
⠋ Buildingapp.import is not a function
TypeError: app.import is not a function
    at Class.module.exports.included (/Users/tchak/git/github/ember-cli/ember-ajax/node_modules/ember-network/index.js:17:15)
    at /Users/tchak/git/github/ember-cli/ember-ajax/node_modules/ember-cli/lib/models/addon.js:244:32
```

Steps to reproduce:
- create a new addon
- `ember install ember-network`
- `ember test`
- :bomb:

**Comment by pittst3r** [comment]
PR that fixes this forthcoming.

**Comment by locks** [comment]
From the referenced PRs, I believe this to be fixed. Please let us know if otherwise!
